linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  goimports:
    local-prefixes: github.com/tensorchord/envd/
  revive:
    rules:
      # available rules: https://github.com/mgechev/revive#available-rules
      - name: indent-error-flow
