linters:
  enable:
    - gofmt
    - bodyclose
    - errcheck
    - goimports
    - errorlint
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unparam
    - unused
linters-settings:
  goimports:
    local-prefixes: github.com/tensorchord/envd/
