# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: envd
    main: ./cmd/envd
    binary: envd
    ldflags:
      - -s -w
      - -X github.com/tensorchord/envd/pkg/version.version={{ .Version }}
      - -X github.com/tensorchord/envd/pkg/version.buildDate={{ .Date }}
      - -X github.com/tensorchord/envd/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/tensorchord/envd/pkg/version.gitTreeState=clean
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: envd-ssh
    main: ./cmd/envd-ssh
    binary: envd-ssh
    ldflags:
      - -s -w
      - -X github.com/tensorchord/envd/pkg/version.version={{ .Version }}
      - -X github.com/tensorchord/envd/pkg/version.buildDate={{ .Date }}
      - -X github.com/tensorchord/envd/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/tensorchord/envd/pkg/version.gitTreeState=clean
archives:
  - id: envd
    format: binary
    builds:
      - envd
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  - id: envd-ssh
    format: binary
    builds:
      - envd-ssh
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
dockers:
- image_templates:
  - "ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-amd64"
  use: buildx
  dockerfile: .goreleaser/envd-ssh.Dockerfile
  ids:
  - envd-ssh
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  ids:
  - envd-ssh
  dockerfile: .goreleaser/envd-ssh.Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}
  image_templates:
  - ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-amd64
  - ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-arm64v8
brews:
  - name: 'envd{{ if filter .Prerelease "alpha" }}@alpha{{ end }}'
    ids:
      - envd
    tap:
      owner: tensorchord
      name: homebrew-tap
    commit_author:
      name: TensorChord
      email: envd-maintainers@tensorchord.ai
    folder: Formula
    homepage: https://envd.tensorchord.ai/
    description: Development environment for data science and AI/ML teams
    license: Apache-2.0
    skip_upload: '{{ if filter .Prerelease "rc" }}true{{ else }}false{{ end }}'
    caveats: |
      Please run `envd bootstrap` first to bootstrap
    dependencies:
      - name: go
        type: build
    conflicts:
      - envd{{ with not .Prerelease }}@alpha{{ end }}
    test: |
      system "#{bin}/envd version"
