# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: envd
    main: ./cmd/envd
    binary: envd
    ldflags:
      - -s -w
      - -X github.com/tensorchord/envd/pkg/version.version={{ .Version }}
      - -X github.com/tensorchord/envd/pkg/version.buildDate={{ .Date }}
      - -X github.com/tensorchord/envd/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/tensorchord/envd/pkg/version.gitTreeState=clean
      - -X github.com/tensorchord/envd/pkg/version.gitTag={{ .Tag }}
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: envd-sshd
    main: ./cmd/envd-sshd
    binary: envd-sshd
    ldflags:
      - -s -w
      - -X github.com/tensorchord/envd/pkg/version.version={{ .Version }}
      - -X github.com/tensorchord/envd/pkg/version.buildDate={{ .Date }}
      - -X github.com/tensorchord/envd/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/tensorchord/envd/pkg/version.gitTreeState=clean
archives:
  - id: envd
    format: binary
    builds:
      - envd
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  - id: envd-sshd
    format: binary
    builds:
      - envd-sshd
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
release:
  skip_upload: true

# See https://github.com/tensorchord/envd/issues/908
# brews:
#   - name: envd
#     ids:
#       - envd
#     tap:
#       owner: tensorchord
#       name: homebrew-tap
#     commit_author:
#       name: TensorChord
#       email: envd-maintainers@tensorchord.ai
#     folder: Formula
#     homepage: https://envd.tensorchord.ai/
#     description: Development environment for data science and AI/ML teams
#     license: Apache-2.0
#     skip_upload: auto
#     caveats: |
#       Please run `envd bootstrap` first to bootstrap
#     test: |
#       system "#{bin}/envd version"
