# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy -compat=1.17
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    id: envd
    main: ./cmd/envd
    binary: envd
    ldflags:
      - -s -w 
      - -X github.com/tensorchord/envd/pkg/version.Version={{ .Version }} 
      - -X github.com/tensorchord/envd/pkg/version.Revision={{ .Commit }}
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    id: envd-ssh
    main: ./cmd/envd-ssh
    binary: envd-ssh
    ldflags:
      - -s -w 
      - -X github.com/tensorchord/envd/pkg/version.Version={{ .Version }} 
      - -X github.com/tensorchord/envd/pkg/version.Revision={{ .Commit }}
archives:
  - id: envd
    format: binary
    builds:
      - envd
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  - id: envd-ssh
    format: binary
    builds:
      - envd-ssh
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
  - "ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-amd64"
  use: buildx
  dockerfile: .goreleaser/envd-ssh.Dockerfile
  ids: 
  - envd-ssh
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  ids: 
  - envd-ssh
  dockerfile: .goreleaser/envd-ssh.Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}
  image_templates:
  - ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-amd64
  - ghcr.io/tensorchord/envd-ssh-from-scratch:{{ .Version }}-arm64v8
