blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://envd.tensorchord.ai/docs/get-started/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/tensorchord/envd/discussions/new
    about: Ask a question or start a discussion
  - name: Chat on Discord
    url: https://discord.gg/KqswhpVgdU
    about: Maybe chatting with the community can help
