name: Feature Request
description: Feature request for envd
labels: ["type/feature \U0001F4A1"]
title: "feat: <title>"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do you need this feature?
      description: A clear and concise description of why you need this feature.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.