package ssh

const hostKeyBytes = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCA5Rl8pbONb8jZDHn4psUME06YLiCGYTNgFcymx29jpwAAAJgcOXgoHDl4
KAAAAAtzc2gtZWQyNTUxOQAAACCA5Rl8pbONb8jZDHn4psUME06YLiCGYTNgFcymx29jpw
AAAEA+STcKunFQTwj1JKfHYIVLov03vhnss6BylornmFAAgIDlGXyls41vyNkMefimxQwT
TpguIIZhM2AVzKbHb2OnAAAAFWdhb2NlZ2VnZUBob3RtYWlsLmNvbQ==
-----END OPENSSH PRIVATE KEY-----`
