name: documentation-check

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '**.md'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
