name: nightly

on:
  schedule:
    - cron: '0 2 * * *' # UTC 2:00 every day
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    if: github.repository == 'tensorchord/envd'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions/checkout@v4
      - name: Add license
        run: |
          make addlicense && git add pkg cmd &&
          git diff --cached --exit-code || (echo 'Please run "make addlicense" to verify govet' && exit 1);
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=5m
          version: latest
          # Ref https://github.com/golangci/golangci-lint-action/issues/244
          skip-cache: true
  build:
    name: build
    if: github.repository == 'tensorchord/envd'
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Build
        run: make
  test:
    name: test
    if: github.repository == 'tensorchord/envd'
    env:
      # Disable telemetry.
      ENVD_ANALYTICS: false
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Verify mockgen
        run: |
          make generate && git add pkg &&
          git diff --cached --exit-code || (echo 'Please run "make generate" to verify generate' && exit 1);
      - name: Test
        run: make test
  e2e-cli:
    name: e2e-cli
    if: github.repository == 'tensorchord/envd'
    env:
      # Disable telemetry.
      ENVD_ANALYTICS: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: e2e test
        run: make e2e-cli-test
        env:
          GIT_LATEST_TAG: ${{ steps.get-latest-tag.outputs.tag }}
  e2e-lang:
    name: e2e-lang
    if: github.repository == 'tensorchord/envd'
    env:
      # Disable telemetry.
      ENVD_ANALYTICS: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: e2e test
        run: make e2e-lang-test
        env:
          GIT_LATEST_TAG: ${{ steps.get-latest-tag.outputs.tag }}
  e2e-doc:
    name: e2e-doc
    if: github.repository == 'tensorchord/envd'
    env:
      # Disable telemetry.
      ENVD_ANALYTICS: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: e2e doc test
        run: make e2e-doc-test
        env:
          GIT_LATEST_TAG: ${{ steps.get-latest-tag.outputs.tag }}
